#pragma once

#include <QtGlobal>

#if defined(ZEITERFASSUNGNETWORKLIB_LIBRARY)
#  define ZEITERFASSUNGNETWORKLIB_EXPORT Q_DECL_EXPORT
#else
#  define ZEITERFASSUNGNETWORKLIB_EXPORT Q_DECL_IMPORT
#endif
